version: '3'
services:
  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    links:
      - server

  server:
    depends_on:
      - db
    build: ./server
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: showmanager
    ports:
      - "3306:3306"